name: Run Python script

on:
  push:
    branches:
      - FtC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Setup ffmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg libx264-dev

      - name: Create and activate virtual environment
        run: |
          python -m venv .venv
          source .venv/bin/activate

      - name: Install dependencies
        run: |
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: Run Python script
        run: |
          source .venv/bin/activate
          python3 ./src/python/transcodeVideo.py
        env:
          SHEET_ID: ${{ secrets.SHEET_ID }}
          CHATGPT_API_KEY: ${{ secrets.CHATGPT_API_KEY }}
          LIVEPEER_API_KEY: ${{ secrets.LIVEPEER_API_KEY }}
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

