name: Process Videos and Generate Descriptions

on:
  push:
    branches: [master]

jobs:
  preprocess:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.list-files.outputs.matrix }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Clone GuillaumeFalourd/poc-github-actions PUBLIC repository
        uses: GuillaumeFalourd/clone-github-repo-action@v2.1
        with:
          depth: 1
          owner: "streamethorg"
          repository: "streameth-platform"

      - name: Create and activate virtual environment
        run: |
          python -m venv .venv

      - name: List batches of files without description and set matrix
        id: list-files
        run: |
          batches=$(python ./python/workflow/list_files_without_description.py)
          echo "matrix=$batches" >> "$GITHUB_OUTPUT"

  process_descriptions:
    needs: preprocess
    runs-on: ubuntu-latest
    strategy:
      matrix:
        files: ${{fromJson(needs.preprocess.outputs.matrix)}}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Clone GuillaumeFalourd/poc-github-actions PUBLIC repository
        uses: GuillaumeFalourd/clone-github-repo-action@v2.1
        with:
          depth: 1
          owner: "streamethorg"
          repository: "streameth-platform"

      - name: Setup ffmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg libx264-dev

      - name: Create and activate virtual environment
        run: |
          python -m venv .venv
          source .venv/bin/activate

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Generate descriptions for a batch of files
        run: |
          python3 ./python/transcodeVideo.py "${{needs.preprocess.outputs.matrix}}" ${{ matrix.files.batchID }}
        env:
          CHATGPT_API_KEY: ${{ secrets.CHATGPT_API_KEY }}

      - name: Make decoy text file
        run: echo "Hello world" > aTextFile.txt

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Prettier
        run: npm --prefix ./streameth-platform install prettier

      - name: Run Prettier using npm script
        run: |
          npm --prefix ./streameth-platform run prettier:fix

      - name: Configure git user
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Commit and Push changes in streameth-platform directory
        working-directory: ./streameth-platform
        run: |
          git checkout -b automatedDescriptions
          git add -A
          git commit -m "Automatically generated video descriptions and formatted with Prettier"
          git push --set-upstream origin automatedDescriptions

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: "Automated PR of AI made descriptions"
          branch: automatedDescriptions
          base: main
          path: ./streameth-platform
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          commit-message: Automated description made by Shorten
          delete-branch: true
          labels: automated pr
          token: ${{ secrets.GITHUB_TOKEN }}
