name: Process Videos and Generate Descriptions

on:
  push:
    branches: [master]

jobs:
  preprocess:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.list-files.outputs.matrix }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Clone GuillaumeFalourd/poc-github-actions PUBLIC repository
        uses: GuillaumeFalourd/clone-github-repo-action@v2.1
        with:
          depth: 1
          owner: 'streamethorg'
          repository: 'streameth-platform'

      - name: Setup ffmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg libx264-dev

      - name: Create and activate virtual environment
        run: |
          python -m venv .venv

      - name: List batches of files without description and set matrix
        id: list-files
        run: |
          batches=$(python ./python/workflow/list_files_without_description.py)
          echo "::set-output name=matrix::$batches"
      

  process_descriptions:
    needs: preprocess
    runs-on: ubuntu-latest
    strategy:
      matrix:
        batch: ${{fromjson(needs.preprocess.outputs.matrix)}}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # - name: Print Matrix
      #   run: |
      #     echo ${{ needs.preprocess.outputs.matrix }}

      - name: Create and activate virtual environment
        run: |
          python -m venv .venv
          source .venv/bin/activate

      - name: Install dependencies
        run: |
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: Generate descriptions for a batch of files
        run: |
          source .venv/bin/activate
          for file in ${{ matrix.batches }}
          do
            python3 ./python/transcodeVideo.py $file
          done
        env:
          SHEET_ID: ${{ secrets.SHEET_ID }}
          CHATGPT_API_KEY: ${{ secrets.CHATGPT_API_KEY }}
          LIVEPEER_API_KEY: ${{ secrets.LIVEPEER_API_KEY }}
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Prettier
        run: npm install prettier

      - name: Run Prettier using npm script
        run: npm run prettier:fix

      - name: Configure git user
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      - name: Commit changes
        run: |
          git add -A
          git commit -m "Automatically generated video descriptions and formatted with Prettier" || echo "No changes to commit"

      - name: Push changes
        run: git push

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: main
          commit-message: Automated description
          delete-branch: true
          labels: automated pr
          token: ${{ secrets.GITHUB_TOKEN }}
